### ISSUE TITLE
Add github action to run tests

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#127]

**Comment by ayanginet** [comment]
I just noticed that Circle CI is disabled, what happened to it?

**Comment by ligi** [comment]
@ayanginet unsure - I never used CircleCI - https://github.com/esPass/pretix-eth-payment-plugin/pull/126#issuecomment-756170236

**Comment by pipermerriam** [comment]
I think that it is enabled, but not configured to run against forks. An admin of this org/repository will need to change that setting to get CI builds to happen on PR's that come from forks.

**Comment by ayanginet** [comment]
So far I implemented a basic workflow for current checks using tox. However, actions are being triggered in the base repo but work fine on forks. [This](https://github.community/t/run-a-github-action-on-pull-request-for-pr-opened-from-a-forked-repo/16054) suggests that it is possible because Github Actions are not enabled in the settings. @ligi could you take a look at the settings? Thanks!

**Comment by ligi** [comment]
Actions are enabled - are you sure it is not just deactivated because it's a draft PR?

**Comment by ayanginet** [comment]
It was the same before I moved it into the draft. Also, checks are running on my [draft PR on fork](https://github.com/ayanginet/pretix-eth-payment-plugin/pull/1).

Anyway, I will keep looking.

**Comment by pipermerriam** [comment]
@ligi double check the permissions.  There's often additional configuration needed to enable things to run on forks since it can be a security concern since sometimes things like API keys are part of the CI process and thus, enabling it on forks can expose those values to 3rd parties.

**Comment by ayanginet** [comment]
@ligi any updates on permissions?

**Comment by ligi** [comment]
actions are running
