### ISSUE TITLE
KeyError 'currency_type'

### ISSUE THREAD

**Issue by ligi** [esPass/pretix-eth-payment-plugin#68]
> had a pending payment. wanted to change from DAI to ETH.. decided to do it later, clicked cancel.

```

Request Method: | GET
-- | --
2.2.2
KeyError
'currency_type'
/var/pretix/venv/lib/python3.7/site-packages/pretix_eth/payment.py in payment_pending_render, line 221
/var/pretix/venv/bin/python3
3.7.3
['/var/pretix',  '/var/pretix',  '/var/pretix/venv/bin',  '/usr/local/lib/python37.zip',  '/usr/local/lib/python3.7',  '/usr/local/lib/python3.7/lib-dynload',  '/var/pretix/venv/lib/python3.7/site-packages']
Thu, 18 Jul 2019 15:36:14 +0000


```

@pipermerriam @davesque can you have a look? This one would be quite urgent - but I can't look at it in the next 4h

**Comment by davesque** [comment]
@ligi Where did that description of the way it was encountered come from?  I'm trying to recreate this and not having any success.  Also, it looks like the majority of instances of this error only affected a few IP addresses.

**Comment by ligi** [comment]
I was contacted by a user. I will try to get him here - but he might be busy with allcoredevs a bit today.

**Comment by tintinweb** [comment]
Hi @davesque,

I've reported that issue. This may help to reproduce:

* buy ticket, select payment DAI, follow process until you receive the confirmation mail.
* go to ticket payment status link (from mail or wherever), change payment, select ETH, change your mind and either cancel or not cancel but just refresh the window.

let me know if you want me to try this on your staging instance.

cheers,
tin

**Comment by davesque** [comment]
@tintinweb Still can't duplicate this issue.  A few questions:

1. When you say, "go to ticket payment status link", do you mean you're visiting a link in the email you received that looks like this: `https://pretix.devcon.org/EF/devcon-5/order/<order code>/<some id>/open/<another id>/`?
2. What are you doing when you "change payment, select ETH, change your mind", etc.?  I need to know exactly the interface items you're clicking on.  A series of screenshots (please make sure you ***DO NOT*** include any personal info in the screenshots) with the interface elements identified will be helpful.  Otherwise, it's hard for me to know exactly what's happening here.

**Comment by ligi** [comment]
I think it would also help to invite him to the staging instance and see if he is able to reproduce this on staging. This would also solve any privacy problem.

**Comment by davesque** [comment]
@tintinweb @ligi Actually, nevermind I think I just got the error.
